import {DriverHistoryRecord} from "@/commons/types/DriverType";
import {EXPERIENCE_LEVEL, RISK_LEVEL, STATUS, vehicleType} from "@/commons/constants/enums";

export function getDriverHistoryRecord():DriverHistoryRecord[]{
    return [
        {
            id: "h1",
            driverId: "1",
            name: "Ana Martínez",
            image: "/assets/ana_martinez.png",
            licenseNumber: "C52224957",
            vehicleType:vehicleType.CAMION_CARGA,
            totalTrips: 2156,
            experienceLevel: EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 12,
            averageAttentionScore: 89,
            lastActiveDate: "2025-01-07",
            status: STATUS.ACTIVO,
            incidentsCount: 2,
            tipoviaje: "Viajes Largos",
            riskLevel: RISK_LEVEL.BAJO,
            totalHoursDriven: 12450,
            fatigueIncidents: 3,
        },
        {
            id: "h2",
            driverId: "1",
            name: "Carlos Rodríguez",
            image: "/assets/carlos_rodriguez.png",
            licenseNumber: "B78425672",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 1247,
            experienceLevel: EXPERIENCE_LEVEL.INTERMEDIO,
            yearsExperience: 8,
            averageAttentionScore: 72,
            lastActiveDate: "2025-01-07",
            status: STATUS.ACTIVO,
            incidentsCount: 8,
            tipoviaje: "Viajes Cortos",
            riskLevel: RISK_LEVEL.MEDIO,
            totalHoursDriven: 7840,
            fatigueIncidents: 12,
        },
        {
            id: "h3",
            driverId: "3",
            name: "Luis Fernández",
            image: "/assets/luis_fernandez.png",
            licenseNumber: "B55667788",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 2156,
            experienceLevel:  EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 12,
            averageAttentionScore: 58,
            lastActiveDate: "2025-01-07",
            status: STATUS.ACTIVO,
            incidentsCount: 15,
            tipoviaje: "Viajes Medianos",
            riskLevel: RISK_LEVEL.ALTO,
            totalHoursDriven: 18920,
            fatigueIncidents: 28,
        },
    ]
}