import {Driver} from "@/commons/types/DriverType";
import {ATTENTION_LEVEL, EXPERIENCE_LEVEL, vehicleType} from "@/commons/constants/enums";
import {joinRoute} from "@/util/currentRoute";
import {CONSTANTS} from "@/commons/constants/constants";
import AttentionByDistanceChart from "@/components/grafic";


export function driverData():Driver[]{
    return [
        {
            id: "1",
            name: "Carlos Rodríguez",
            image:  "/assets/carlos_rodriguez.png",
            attentionLevel: ATTENTION_LEVEL.OPTIMO,
            attentionScore: 92,
            fatigueLevel: 15,
            lastUpdate: CONSTANTS.LAST_UPDATE,
            licenseNumber: "B78425672",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 1247,
            experienceLevel: EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 8,
            lastTripDate: "2025-01-07",
            safetyScore: 98,
            currentRoute: joinRoute(CONSTANTS.CITY_COMD,CONSTANTS.CITY_CDMX),
            estimatedDistance: 985,
            isOnDuty: true,
            shiftStartTime: "06:00",
            hoursOnDuty: 4.5,
            alertnessData:


             [
                { timestamp: "6:00", attentionScore: 95, eyeMovement: 88, headPosition: 92, blinkRate: 18, yawnCount: 0 },
                { timestamp: "6:15", attentionScore: 92, eyeMovement: 85, headPosition: 90, blinkRate: 20, yawnCount: 1 },
                { timestamp: "6:30", attentionScore: 94, eyeMovement: 90, headPosition: 88, blinkRate: 19, yawnCount: 0 },
                { timestamp: "6:45", attentionScore: 91, eyeMovement: 87, headPosition: 89, blinkRate: 22, yawnCount: 1 },
                { timestamp: "6:00", attentionScore: 93, eyeMovement: 89, headPosition: 91, blinkRate: 20, yawnCount: 0 },
            ],
        },
        {
            id: "2",
            name: "Bruno Gonzales",
            image: "/assets/bruno_gonzales.png",
            attentionLevel: ATTENTION_LEVEL.MODERADO,
            attentionScore: 68,
            fatigueLevel: 45,
            lastUpdate: CONSTANTS.LAST_UPDATE,
            licenseNumber: "CD6495672",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 892,
            experienceLevel: EXPERIENCE_LEVEL.INTERMEDIO,
            yearsExperience: 5,
            lastTripDate: "2025-01-07",
            safetyScore: 76,
            currentRoute: joinRoute(CONSTANTS.CITY_COMD,CONSTANTS.CITY_TAB),
            estimatedDistance: 451,
            isOnDuty: true,
            shiftStartTime: "12:00",
            hoursOnDuty: 3.5,
            alertnessData: [
                { timestamp: "12:00", attentionScore: 72, eyeMovement: 65, headPosition: 70, blinkRate: 28, yawnCount: 3 },
                { timestamp: "12:15", attentionScore: 68, eyeMovement: 62, headPosition: 68, blinkRate: 32, yawnCount: 4 },
                { timestamp: "12:30", attentionScore: 70, eyeMovement: 68, headPosition: 72, blinkRate: 30, yawnCount: 2 },
                { timestamp: "12:45", attentionScore: 65, eyeMovement: 60, headPosition: 65, blinkRate: 35, yawnCount: 5 },
                { timestamp: "13:00", attentionScore: 68, eyeMovement: 64, headPosition: 69, blinkRate: 33, yawnCount: 3 },
            ],
        },
        {
            id: "3",
            name: "Ana Martínez",
            image: "/assets/ana_martinez.png",
            attentionLevel: ATTENTION_LEVEL.CRITICO,
            attentionScore: 35,
            fatigueLevel: 85,
            lastUpdate: CONSTANTS.LAST_UPDATE,
            licenseNumber: "C52224957",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 2156,
            experienceLevel: EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 12,
            lastTripDate: "2024-01-07",
            safetyScore: 58,
            currentRoute: joinRoute(CONSTANTS.CITY_COMD,CONSTANTS.CITY_OAX),
            estimatedDistance: 707,
            isOnDuty: true,
            shiftStartTime: "14:00",
            hoursOnDuty: 5.3,
            alertnessData: [
                { timestamp: "14:00", attentionScore:45, eyeMovement: 40, headPosition: 42, blinkRate: 45, yawnCount: 8 },
                { timestamp: "14:15", attentionScore: 38, eyeMovement: 35, headPosition: 38, blinkRate: 50, yawnCount: 12 },
                { timestamp: "14:30", attentionScore: 42, eyeMovement: 38, headPosition: 40, blinkRate: 48, yawnCount: 10 },
                { timestamp: "14:45", attentionScore: 32, eyeMovement: 30, headPosition: 35, blinkRate: 55, yawnCount: 15 },
                { timestamp: "15:00", attentionScore: 35, eyeMovement: 32, headPosition: 37, blinkRate: 52, yawnCount: 13 },
            ],
        },
        {
            id: "4",
            name: "Luis Fernández",
            image: "/assets/luis_fernandez.png",
            attentionLevel:ATTENTION_LEVEL.OPTIMO,
            attentionScore: 88,
            fatigueLevel: 20,
            lastUpdate: CONSTANTS.LAST_UPDATE,
            licenseNumber: "B-55667788",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 1856,
            experienceLevel: EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 15,
            lastTripDate: "2024-01-07",
            safetyScore: 91,
            currentRoute: joinRoute(CONSTANTS.CITY_COMD,CONSTANTS.CITY_TGZ),
            estimatedDistance: 149,
            isOnDuty: true,
            shiftStartTime: "08:00",
            hoursOnDuty: 3.2,
            alertnessData: [
                { timestamp: "8:00",  attentionScore: 90, eyeMovement: 85, headPosition: 88, blinkRate: 20, yawnCount: 1 },
                { timestamp: "14:15", attentionScore: 88, eyeMovement: 82, headPosition: 86, blinkRate: 22, yawnCount: 2 },
                { timestamp: "14:30", attentionScore: 89, eyeMovement: 84, headPosition: 87, blinkRate: 21, yawnCount: 1 },
                { timestamp: "14:45", attentionScore: 86, eyeMovement: 80, headPosition: 85, blinkRate: 24, yawnCount: 3 },
                { timestamp: "15:00", attentionScore: 88, eyeMovement: 83, headPosition: 86, blinkRate: 23, yawnCount: 2 },
            ],
        },
        {
            id: "5",
            name: "Sofia López",
            image: "/assets/sofia_lopez.png",
            attentionLevel: ATTENTION_LEVEL.MODERADO,
            attentionScore: 72,
            fatigueLevel: 38,
            lastUpdate: "Hace 45 segundos",
            licenseNumber: "A99887766",
            vehicleType: vehicleType.CAMION_CARGA,
            totalTrips: 1423,
            experienceLevel: EXPERIENCE_LEVEL.INTERMEDIO,
            yearsExperience: 7,
            lastTripDate: "2024-01-07",
            safetyScore: 82,
            currentRoute: joinRoute(CONSTANTS.CITY_COMD,CONSTANTS.CITY_PUE),
            estimatedDistance: 852,
            isOnDuty: true,
            shiftStartTime: "09:00",
            hoursOnDuty: 2.8,
            alertnessData: [
                { timestamp: "14:00", attentionScore: 75, eyeMovement: 70, headPosition: 73, blinkRate: 26, yawnCount: 2 },
                { timestamp: "14:15", attentionScore: 72, eyeMovement: 68, headPosition: 71, blinkRate: 28, yawnCount: 3 },
                { timestamp: "14:30", attentionScore: 74, eyeMovement: 72, headPosition: 74, blinkRate: 27, yawnCount: 2 },
                { timestamp: "14:45", attentionScore: 70, eyeMovement: 66, headPosition: 69, blinkRate: 30, yawnCount: 4 },
                { timestamp: "15:00", attentionScore: 72, eyeMovement: 69, headPosition: 72, blinkRate: 29, yawnCount: 3 },
            ],
        },
    ]

}