import {DriverHistoryRecord} from "@/commons/types/DriverType";
import {EXPERIENCE_LEVEL, RISK_LEVEL, STATUS} from "@/commons/constants/enums";

export function getDriverHistoryRecord():DriverHistoryRecord[]{
    return [
        {
            id: "h1",
            driverId: "1",
            name: "María González",
            image: "/placeholder.svg?height=80&width=80",
            licenseNumber: "B-12345678",
            vehicleType: "Camión de carga",
            totalTrips: 1247,
            experienceLevel: EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 8,
            averageAttentionScore: 89,
            lastActiveDate: "2024-01-07",
            status: STATUS.ACTIVO,
            incidentsCount: 2,
            perfectTripsPercentage: 94,
            riskLevel: RISK_LEVEL.BAJO,
            totalHoursDriven: 12450,
            fatigueIncidents: 3,
        },
        {
            id: "h2",
            driverId: "2",
            name: "Carlos Rodríguez",
            image: "/placeholder.svg?height=80&width=80",
            licenseNumber: "A-87654321",
            vehicleType: "Autobús urbano",
            totalTrips: 892,
            experienceLevel: EXPERIENCE_LEVEL.INTERMEDIO,
            yearsExperience: 5,
            averageAttentionScore: 72,
            lastActiveDate: "2024-01-07",
            status: STATUS.ACTIVO,
            incidentsCount: 8,
            perfectTripsPercentage: 78,
            riskLevel: RISK_LEVEL.MEDIO,
            totalHoursDriven: 7840,
            fatigueIncidents: 12,
        },
        {
            id: "h3",
            driverId: "3",
            name: "Ana Martínez",
            image: "/placeholder.svg?height=80&width=80",
            licenseNumber: "C-11223344",
            vehicleType: "Taxi",
            totalTrips: 2156,
            experienceLevel:  EXPERIENCE_LEVEL.EXPERTO,
            yearsExperience: 12,
            averageAttentionScore: 58,
            lastActiveDate: "2024-01-07",
            status: STATUS.ACTIVO,
            incidentsCount: 15,
            perfectTripsPercentage: 62,
            riskLevel: RISK_LEVEL.ALTO,
            totalHoursDriven: 18920,
            fatigueIncidents: 28,
        },
    ]
}